import "./globals.css";
import { CityProvider } from "../Context/WeatherContext";
import { Share_Tech_Mono } from "next/font/google";

const shareTechMono = Share_Tech_Mono({
  variable: "--font-share-tech",
  subsets: ["latin"],
  weight: "400",
});


export const metadata = {
  title: "Cloudy - Weather App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${shareTechMono.variable}  antialiased flex items-center justify-center select-none md:overflow-hidden`}
      >
        <CityProvider>
          {children}
        </CityProvider>
      </body>
    </html>
  );
}
